name: build-test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci-lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Install Go
       uses: actions/setup-go@v3
       with:
         # https://github.com/actions/setup-go#supported-version-syntax
         # ex:
         # - 1.18beta1 -> 1.18.0-beta.1
         # - 1.18rc1 -> 1.18.0-rc.1
         go-version: ${{ env.GO_VERSION }}
     - name: lint
       uses: golangci/golangci-lint-action@v3.2.0
       with:
         version: latest
         # skip cache because of flaky behaviors
         skip-build-cache: true
         skip-pkg-cache: true
